services:

  duatic-docker-image:
    image: ghcr.io/duatic/duatic-docker-image-local
    container_name: duatic-docker-image-local
    build:
      context: .
      dockerfile: ./docker/Dockerfile.jazzy
    environment:
      DISPLAY: ${DISPLAY:-:0}
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856 
    stdin_open: true
    tty: true
    volumes:      
      - /etc/security/limits.conf:/etc/security/limits.conf
      - /tmp/.X11-unix:/tmp/.X11-unix